document.addEventListener('DOMContentLoaded',async()=>{
const S={products:[],filteredProducts:[],cart:[],user:null,currentView:'home',searchQuery:'',selectedCategory:'All',wishlist:[]};
const appView=document.getElementById('app-view');
const cartDrawer=document.getElementById('cart-drawer');
const cartOverlay=document.getElementById('cart-overlay');
const cartItemsEl=document.getElementById('cart-items');
const toastEl=document.getElementById('toast');
// Particles (Clean, slow, stardust effect)
const cv=document.getElementById('particle-canvas');
if(cv){const cx=cv.getContext('2d');let pts=[];
const resize=()=>{cv.width=window.innerWidth;cv.height=window.innerHeight};
resize();window.addEventListener('resize',resize);
for(let i=0;i<35;i++)pts.push({x:Math.random()*cv.width,y:Math.random()*cv.height,vx:(Math.random()-.5)*.1,vy:(Math.random()-.5)*.1,r:Math.random()*1.2+0.4});
(function draw(){cx.clearRect(0,0,cv.width,cv.height);pts.forEach((p)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>cv.width)p.vx*=-1;if(p.y<0||p.y>cv.height)p.vy*=-1;cx.beginPath();cx.arc(p.x,p.y,p.r,0,Math.PI*2);cx.fillStyle='rgba(212,168,83,0.22)';cx.fill()});requestAnimationFrame(draw)})()}
// Three.js hero (Elegant Floating Crystal Core)
function init3D(container){if(!container||typeof THREE==='undefined')return;const w=container.clientWidth,h=container.clientHeight;const scene=new THREE.Scene();const cam=new THREE.PerspectiveCamera(60,w/h,.1,100);cam.position.z=4.5;const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setSize(w,h);renderer.setPixelRatio(window.devicePixelRatio);container.appendChild(renderer.domElement);
const wireMat=new THREE.MeshBasicMaterial({color:0xd4a853,wireframe:true,transparent:true,opacity:.35});
const solidMat=new THREE.MeshBasicMaterial({color:0xf0d48a,transparent:true,opacity:.08,wireframe:false});
const outerCrystal=new THREE.Mesh(new THREE.IcosahedronGeometry(1.5,0),wireMat);scene.add(outerCrystal);
const innerCore=new THREE.Mesh(new THREE.IcosahedronGeometry(0.7,1),solidMat);scene.add(innerCore);
let time=0;
(function anim(){requestAnimationFrame(anim);time+=0.004;outerCrystal.rotation.y+=0.0015;outerCrystal.rotation.x+=0.0008;innerCore.rotation.y-=0.0025;outerCrystal.position.y=Math.sin(time)*0.12;innerCore.position.y=Math.sin(time)*0.12;renderer.render(scene,cam)})()}
// Fetch
async function fetchData(){try{const[p,c]=await Promise.all([fetch('/api/products'),fetch('/api/cart')]);S.products=await p.json();S.filteredProducts=[...S.products];S.cart=await c.json();renderHome();updateCartUI()}catch(e){console.error(e);renderHome()}}
// Filters
function applyFilters(){S.filteredProducts=S.products.filter(p=>{const ms=p.name.toLowerCase().includes(S.searchQuery);const mc=S.selectedCategory==='All'||p.category===S.selectedCategory;return ms&&mc});if(S.currentView==='shop')renderShop()}
window.handleSearch=q=>{S.searchQuery=q.toLowerCase();const dd=document.getElementById('search-dropdown');if(q.length>0){const res=S.products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).slice(0,5);if(res.length){dd.innerHTML=res.map(p=>`<div class="search-item" onclick="viewProductDetail(${p.id})">`+`<img src="${p.img}"><div><div style="font-weight:600">${p.name}</div>`+`<div style="color:var(--gold);font-size:13px">₹${p.price.toLocaleString()}</div></div></div>`).join('');dd.classList.add('open')}else dd.classList.remove('open')}else dd.classList.remove('open');applyFilters()};
// Nav
function navigate(view){if(view==='account'&&!S.user)view='login';S.currentView=view;document.querySelectorAll('.nav-link').forEach(l=>l.classList.toggle('active',l.dataset.view===view));appView.style.opacity='0';setTimeout(()=>{renderView(view);appView.style.opacity='1';window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>{document.querySelectorAll('.reveal').forEach((el,i)=>{setTimeout(()=>el.classList.add('visible'),i*80)})},100)},250)}
function renderView(v){if(v==='travel')return renderTravel();if(v==='login')return renderLogin();if(v==='register')return renderRegister();if(v==='shop')return renderShop();if(v==='account')return renderAccount();renderHome()}
// Cards
function productCard(p){const w=S.wishlist.includes(p.id);return`<div class="product-card reveal" onmouseenter="tiltIn(this,event)" onmousemove="tiltMove(this,event)" onmouseleave="tiltOut(this)"><img class="card-img" src="${p.img}" alt="${p.name}" onclick="viewProductDetail(${p.id})"><div class="card-cat">${(p.category||'').toUpperCase()}</div><div class="card-name">${p.name}</div><div class="card-price">₹${p.price.toLocaleString()}</div><div class="card-actions"><button class="card-btn ${w?'wishlisted':''}" onclick="toggleWish(${p.id})"><i class="fas fa-heart"></i></button><button class="card-btn" onclick="addToCart(${p.id})"><i class="fas fa-plus"></i></button></div></div>`}
// 3D tilt
window.tiltIn=function(el){el.style.transition='none'};
window.tiltMove=function(el,e){const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(800px) rotateY(${x*12}deg) rotateX(${-y*12}deg) translateY(-8px)`;el.style.boxShadow=`${-x*20}px ${y*20}px 40px rgba(0,0,0,.4), 0 0 30px rgba(212,168,83,.15)`};
window.tiltOut=function(el){el.style.transition='all .4s';el.style.transform='';el.style.boxShadow=''};
// Wishlist
window.toggleWish=function(id){const i=S.wishlist.indexOf(id);if(i>-1){S.wishlist.splice(i,1);showToast('Removed from wishlist')}else{S.wishlist.push(id);showToast('Added to wishlist')}if(S.currentView==='shop')renderShop();else renderHome()};
// Render Home
function renderHome(){appView.innerHTML=`<div class="container"><section class="hero-section reveal"><div class="hero-content"><div class="hero-tag">✦ RIOUK ELITE COLLECTION</div><h1 class="hero-title">Discover <span class="gold">Luxury</span><br>Redefined</h1><p class="hero-desc">Experience the future of premium shopping with our curated collection of elite tech, fashion, and lifestyle products.</p><div style="display:flex;gap:16px"><button class="btn-primary" onclick="navigate('shop')">EXPLORE SHOP</button><button class="btn-outline" onclick="navigate('travel')">TRAVEL HUB</button></div></div><div id="hero-3d"></div></section>`+
`<section class="reveal"><div class="section-header"><h2>Categories</h2></div><div class="categories-row">${[{n:'Drops',i:'fa-bolt',d:'Latest releases'},{n:'Gear',i:'fa-tshirt',d:'Premium fashion'},{n:'Tech',i:'fa-microchip',d:'Elite gadgets'},{n:'Elite',i:'fa-gem',d:'Luxury picks'}].map(c=>`<div class="cat-card" onclick="S.selectedCategory='${c.n}';navigate('shop')"><div class="cat-icon"><i class="fas ${c.i}"></i></div><h4>${c.n}</h4><p>${c.d}</p></div>`).join('')}</div></section>`+
`<section class="reveal"><div class="section-header"><h2>Featured Products</h2><a href="#" class="view-all" onclick="event.preventDefault();navigate('shop')">View All →</a></div><div class="products-grid">${S.products.slice(0,8).map(p=>productCard(p)).join('')}</div></section>`+
`<section class="reveal"><div class="section-header"><h2>Elite Offers</h2><span class="view-all">SWIPE FOR DEALS</span></div><div class="deals-scroll">${S.products.slice(0,4).map((p,i)=>`<div class="deal-card" style="position:relative" onclick="viewProductDetail(${p.id})"><div class="deal-tag">${['50% OFF','HOT','NEW','ELITE'][i]}</div><img src="${p.img}"><div class="deal-info"><h4>${p.name}</h4><p>${p.description||'Premium product'}</p><div class="deal-price">₹${p.price.toLocaleString()}</div></div></div>`).join('')}</div></section>`+
`<section class="banner-section reveal"><div class="banner-text"><h2>Become an <span style="color:var(--gold)">Riouk Elite</span> Member</h2><p>Get exclusive early access, premium discounts, and priority shipping on all orders.</p><button class="btn-primary" onclick="navigate('register')">JOIN NOW — FREE</button></div><div style="font-size:80px;color:var(--gold);opacity:.3"><i class="fas fa-crown"></i></div></section>`+renderFooter()+`</div>`;
setTimeout(()=>init3D(document.getElementById('hero-3d')),100)}
// Shop
function renderShop(){appView.innerHTML=`<div class="container"><div class="section-header reveal"><h2>${S.selectedCategory==='All'?'All':S.selectedCategory} Marketplace</h2><span style="color:var(--muted)">${S.filteredProducts.length} items</span></div><div style="display:flex;gap:10px;margin-bottom:32px;flex-wrap:wrap" class="reveal">${['All','Drops','Gear','Tech','Elite'].map(c=>`<button onclick="S.selectedCategory='${c}';applyFilters();renderShop()" style="padding:10px 20px;border-radius:10px;border:1px solid ${S.selectedCategory===c?'var(--gold)':'var(--glass-border)'};background:${S.selectedCategory===c?'rgba(212,168,83,.15)':'var(--glass)'};color:${S.selectedCategory===c?'var(--gold)':'var(--muted)'};cursor:pointer;font-weight:600;font-size:13px;transition:.3s">${c}</button>`).join('')}</div><div class="products-grid">${S.filteredProducts.length?S.filteredProducts.map(p=>productCard(p)).join(''):'<p style="grid-column:1/-1;text-align:center;padding:60px;color:var(--muted)">No products found.</p>'}</div>${renderFooter()}</div>`}
// Travel
function renderTravel(){appView.innerHTML=`<div class="container"><section class="reveal"><div class="section-header"><h2>Travel Hub</h2><div style="display:flex;align-items:center;gap:6px;color:var(--gold)"><i class="fas fa-coins"></i><span style="font-weight:700">0 points</span></div></div><div class="travel-categories">${[{t:'Flights',d:'Up to 25% Off',c:'linear-gradient(135deg,#6C63FF,#3B82F6)',i:'travel_flights.png'},{t:'Hotels',d:'Up to 65% Off',c:'linear-gradient(135deg,#F59E0B,#EF4444)',i:'travel_hotels.png'},{t:'Buses',d:'Up to 25% Off',c:'linear-gradient(135deg,#10B981,#059669)',i:'travel_buses.png'}].map(x=>`<div class="travel-cat-card" style="background:${x.c}" onclick="showTravelBooking('${x.t.toLowerCase().slice(0,-1)}')"><div class="travel-cat-info"><h4>${x.t}</h4><span class="travel-discount">${x.d}</span></div><img src="${x.i}"></div>`).join('')}</div></section>`+
`<section class="reveal" style="margin-top:24px"><div class="section-header"><h2>Travel Deals</h2><span class="view-all">SWIPE</span></div><div class="deals-scroll">${[{t:'Delhi → Mumbai',s:'Non-stop • 2h 10m',p:'₹2,499',i:'travel_flights.png',b:'flight'},{t:'Goa Beach Resort',s:'5-Star • 2 Nights',p:'₹8,999',i:'travel_hotels.png',b:'hotel'},{t:'Bangalore → Chennai',s:'AC Sleeper • 6h',p:'₹899',i:'travel_buses.png',b:'bus'},{t:'Manali Retreat',s:'4-Star • 3 Nights',p:'₹12,499',i:'travel_hotels.png',b:'hotel'}].map(d=>`<div class="travel-deal-card" onclick="showTravelBooking('${d.b}')"><img src="${d.i}"><div class="travel-deal-info"><h4>${d.t}</h4><p>${d.s}</p><div class="travel-deal-price">${d.p}</div></div></div>`).join('')}</div></section>`+
`<section class="banner-section reveal" style="margin-top:32px;background:linear-gradient(135deg,#7C3AED,#EC4899)"><div class="banner-text"><h2 style="color:#fff">Flash Sale</h2><p style="color:rgba(255,255,255,.7)">Exclusive travel deals — limited time only!</p><button class="btn-primary" style="background:#fff;color:#7C3AED" onclick="showToast('Flash sale coming soon!')">VIEW DEALS</button></div><div style="font-size:64px;opacity:.4">⚡</div></section>${renderFooter()}</div>`}
// Account
async function renderAccount(){if(!S.user)return navigate('login');let orders=[];try{const r=await fetch('/api/orders');orders=await r.json()}catch(e){}
appView.innerHTML=`<div class="container"><div class="reveal" style="text-align:center;padding-top:40px"><div style="width:100px;height:100px;background:var(--gradient);border-radius:50%;margin:0 auto 20px;display:flex;align-items:center;justify-content:center;font-size:40px;box-shadow:0 10px 30px var(--gold-glow)"><i class="fas fa-user-circle"></i></div><h2>${S.user.name}</h2><p style="color:var(--muted)">${S.user.email}</p></div><div style="margin-top:40px" class="reveal"><div class="section-header"><h2>Order History</h2></div>${orders.length===0?'<p style="color:var(--muted);text-align:center;padding:40px">No orders yet.</p>':orders.map(o=>`<div class="glass-card" style="padding:20px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:12px;color:var(--muted)">${new Date(o.order_date).toLocaleDateString()}</div><div style="font-weight:700">Order #${o.id}</div></div><div style="text-align:right"><div style="color:var(--gold2);font-weight:700">₹${o.total_amount.toLocaleString()}</div><div style="font-size:11px;color:var(--muted)">${o.items_count} items</div></div></div>`).join('')}<div class="glass-card reveal" style="padding:20px;color:#e74c3c;text-align:center;margin-top:32px;cursor:pointer;font-weight:700" onclick="S.user=null;navigate('home');showToast('Logged out')">LOGOUT</div></div>${renderFooter()}</div>`}
// Login
function renderLogin(){appView.innerHTML=`<div class="container" style="max-width:480px;margin:0 auto;padding-top:80px"><div class="glass-card reveal" style="padding:48px;text-align:center"><i class="fas fa-shield-halved" style="font-size:48px;color:var(--gold);margin-bottom:24px"></i><h2>Access Riouk</h2><p style="color:var(--muted);margin-bottom:32px">Login to your elite profile</p><div class="input-group"><i class="fas fa-envelope"></i><input type="email" id="login-email" placeholder="Email"></div><div class="input-group"><i class="fas fa-lock"></i><input type="password" id="login-password" placeholder="Password"></div><button onclick="performLogin()" class="btn-primary" style="width:100%">ENTER RIOUK</button><p style="margin-top:20px;color:var(--muted);font-size:14px">New? <span onclick="navigate('register')" style="color:var(--gold);cursor:pointer;font-weight:700">Create Account</span></p></div></div>`}
// Register
function renderRegister(){appView.innerHTML=`<div class="container" style="max-width:480px;margin:0 auto;padding-top:80px"><div class="glass-card reveal" style="padding:48px;text-align:center"><i class="fas fa-user-plus" style="font-size:48px;color:var(--gold);margin-bottom:24px"></i><h2>Join Riouk</h2><p style="color:var(--muted);margin-bottom:32px">Create your elite identity</p><div class="input-group"><i class="fas fa-user"></i><input type="text" id="reg-name" placeholder="Full Name"></div><div class="input-group"><i class="fas fa-envelope"></i><input type="email" id="reg-email" placeholder="Email"></div><div class="input-group"><i class="fas fa-lock"></i><input type="password" id="reg-password" placeholder="Password"></div><button onclick="performSignup()" class="btn-primary" style="width:100%">CREATE IDENTITY</button><p style="margin-top:20px;color:var(--muted);font-size:14px">Already Elite? <span onclick="navigate('login')" style="color:var(--gold);cursor:pointer;font-weight:700">Login</span></p></div></div>`}
// Footer
function renderFooter(){return`<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><div class="brand-text">RIOUK</div><p>The ultimate luxury e-commerce experience. Curated collections for the elite.</p></div><div class="footer-col"><h4>Shop</h4><a href="#" onclick="event.preventDefault();navigate('shop')">All Products</a><a href="#">New Arrivals</a><a href="#">Best Sellers</a></div><div class="footer-col"><h4>Company</h4><a href="#">About Us</a><a href="#">Careers</a><a href="#">Press</a></div><div class="footer-col"><h4>Support</h4><a href="#">Help Center</a><a href="#">Returns</a><a href="#">Contact</a></div></div><div class="footer-bottom"><span>© 2026 RIOUK. All rights reserved.</span><div class="footer-socials"><a href="#"><i class="fab fa-instagram"></i></a><a href="#"><i class="fab fa-twitter"></i></a><a href="#"><i class="fab fa-linkedin"></i></a></div></div></div></footer>`}
// Detail
window.viewProductDetail=id=>{const p=S.products.find(x=>x.id===id);if(!p)return;const dv=document.getElementById('product-detail-view');dv.innerHTML=`<div class="detail-overlay" onclick="closeDetail()"></div><div class="detail-modal"><div class="detail-modal-header"><i class="fas fa-times" onclick="closeDetail()"></i></div><img class="detail-img" src="${p.img}"><div class="detail-body"><div class="cat-label">${(p.category||'').toUpperCase()} COLLECTION</div><h2>${p.name}</h2><div class="price">₹${p.price.toLocaleString()}</div><p class="desc">${p.description||'Premium elite product from the Riouk collection.'}</p><div class="detail-actions"><button class="btn-outline" onclick="addToCart(${p.id});closeDetail()">ADD TO BAG</button><button class="btn-primary" onclick="performInstantBooking(${p.id})">BUY NOW</button></div></div></div>`;dv.classList.add('open');document.getElementById('search-dropdown').classList.remove('open')};
window.closeDetail=()=>document.getElementById('product-detail-view').classList.remove('open');
// Travel booking
window.showTravelBooking=type=>{const t={flight:'Book a Flight',hotel:'Book a Hotel',bus:'Book a Bus'};const c={flight:'#6C63FF',hotel:'#F59E0B',bus:'#10B981'};const ic={flight:'fa-plane',hotel:'fa-hotel',bus:'fa-bus'};const dv=document.getElementById('product-detail-view');dv.innerHTML=`<div class="detail-overlay" onclick="closeDetail()"></div><div class="detail-modal"><div class="detail-modal-header"><i class="fas fa-times" onclick="closeDetail()"></i></div><div style="padding:40px;text-align:center"><div style="width:80px;height:80px;border-radius:50%;background:${c[type]};margin:0 auto 20px;display:flex;align-items:center;justify-content:center;font-size:32px"><i class="fas ${ic[type]}"></i></div><h2>${t[type]}</h2><p style="color:var(--muted);margin-bottom:30px">Find the best ${type} deals</p><div class="input-group"><i class="fas fa-map-marker-alt"></i><input placeholder="${type==='hotel'?'City':'From'}"></div>${type!=='hotel'?'<div class="input-group"><i class="fas fa-map-pin"></i><input placeholder="To"></div>':''}<div class="input-group"><i class="fas fa-calendar"></i><input type="date"></div><div class="input-group"><i class="fas fa-users"></i><input type="number" value="1" min="1" placeholder="${type==='hotel'?'Guests':'Passengers'}"></div><button class="btn-primary" style="width:100%" onclick="closeDetail();showToast('Searching best ${type} deals...')">SEARCH ${type.toUpperCase()}S</button></div></div>`;dv.classList.add('open')};
window.performInstantBooking=async id=>{if(!S.user){closeDetail();return navigate('login')}const p=S.products.find(x=>x.id===id);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({total:p.price,itemsCount:1})});if(r.ok){closeDetail();showToast(`Order Confirmed for ${p.name}!`);navigate('account')}}catch(e){showToast('Booking failed')}};
// Auth
window.performSignup=async()=>{const n=document.getElementById('reg-name').value,e=document.getElementById('reg-email').value,p=document.getElementById('reg-password').value;if(!n||!e||!p)return showToast('Fill all fields');try{const r=await fetch('/api/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n,email:e,password:p})});if(r.ok){S.user=await r.json();showToast(`Welcome ${S.user.name}!`);navigate('account')}else{const d=await r.json();showToast(d.error||'Signup failed')}}catch(e){showToast('Network error')}};
window.performLogin=async()=>{const e=document.getElementById('login-email').value,p=document.getElementById('login-password').value;try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});if(r.ok){S.user=await r.json();showToast(`Welcome back, ${S.user.name}`);navigate('account')}else showToast('Invalid credentials')}catch(e){showToast('Login failed')}};
// Cart
window.addToCart=async id=>{const p=S.products.find(x=>x.id===id);try{const r=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:id})});if(r.ok){S.cart.push(p);updateCartUI();showToast(`Added ${p.name} to bag`)}}catch(e){showToast('Failed')}};
window.removeFromCart=i=>{S.cart.splice(i,1);updateCartUI()};
function updateCartUI(){const total=S.cart.reduce((s,i)=>s+i.price,0);const b=document.getElementById('cart-badge'),t=document.getElementById('cart-total');if(b)b.textContent=S.cart.length;if(t)t.textContent=total.toLocaleString();cartItemsEl.innerHTML=S.cart.length===0?'<p style="color:var(--muted);text-align:center;padding:60px">Your bag is empty</p>':S.cart.map((item,i)=>`<div class="cart-item"><img src="${item.img}"><div class="item-info"><div class="item-name">${item.name}</div><div class="item-price">₹${item.price.toLocaleString()}</div></div><i class="fas fa-trash item-remove" onclick="removeFromCart(${i})"></i></div>`).join('')}
window.processCheckout=async()=>{if(!S.cart.length)return showToast('Bag is empty');const total=S.cart.reduce((s,i)=>s+i.price,0);try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({total,itemsCount:S.cart.length})});if(r.ok){S.cart=[];updateCartUI();cartDrawer.classList.remove('open');cartOverlay.classList.remove('open');showToast('Order Placed!')}}catch(e){showToast('Checkout failed')}};
function showToast(msg){const m=document.getElementById('toast-msg');if(m)m.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),3000)}
window.showToast=showToast;
// Scanner
window.openScanner=mode=>{document.getElementById('scanner-modal').classList.add('open')};
window.closeScanner=()=>{document.getElementById('scanner-modal').classList.remove('open')};
// Events
document.getElementById('global-search').addEventListener('input',e=>handleSearch(e.target.value));
document.addEventListener('click',e=>{if(!document.getElementById('nav-search').contains(e.target))document.getElementById('search-dropdown').classList.remove('open')});
document.querySelectorAll('.nav-link').forEach(l=>l.addEventListener('click',e=>{e.preventDefault();if(l.dataset.view)navigate(l.dataset.view)}));
document.getElementById('nav-brand').addEventListener('click',e=>{e.preventDefault();navigate('home')});
document.getElementById('cart-trigger').addEventListener('click',()=>{cartDrawer.classList.add('open');cartOverlay.classList.add('open')});
document.getElementById('close-cart').addEventListener('click',()=>{cartDrawer.classList.remove('open');cartOverlay.classList.remove('open')});
cartOverlay.addEventListener('click',()=>{cartDrawer.classList.remove('open');cartOverlay.classList.remove('open')});
// Scroll navbar
window.addEventListener('scroll',()=>{document.getElementById('navbar').style.boxShadow=window.scrollY>50?'0 4px 30px rgba(0,0,0,.5)':''});
// Expose
window.navigate=navigate;window.S=S;window.applyFilters=applyFilters;window.renderShop=renderShop;
appView.style.transition='opacity .3s ease';
fetchData()});
